services:
  movie-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_TMDB_API_KEY=${NEXT_PUBLIC_TMDB_API_KEY}
        - NEXT_PUBLIC_TMDB_BASE_URL=${NEXT_PUBLIC_TMDB_BASE_URL}
        - NEXT_PUBLIC_TMDB_IMAGE_BASE_URL=${NEXT_PUBLIC_TMDB_IMAGE_BASE_URL}
        - NEXT_PUBLIC_TMDB_IMAGE_SIZE_POSTER=${NEXT_PUBLIC_TMDB_IMAGE_SIZE_POSTER}
        - NEXT_PUBLIC_TMDB_IMAGE_SIZE_BACKDROP=${NEXT_PUBLIC_TMDB_IMAGE_SIZE_BACKDROP}
        - NEXT_PUBLIC_VIDSRC_BASE_URL=${NEXT_PUBLIC_VIDSRC_BASE_URL}
        - NEXT_PUBLIC_VIDLINK_BASE_URL=${NEXT_PUBLIC_VIDLINK_BASE_URL}
    container_name: movie-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_TMDB_API_KEY=${NEXT_PUBLIC_TMDB_API_KEY}
      - NEXT_PUBLIC_TMDB_BASE_URL=${NEXT_PUBLIC_TMDB_BASE_URL}
      - NEXT_PUBLIC_TMDB_IMAGE_BASE_URL=${NEXT_PUBLIC_TMDB_IMAGE_BASE_URL}
      - NEXT_PUBLIC_TMDB_IMAGE_SIZE_POSTER=${NEXT_PUBLIC_TMDB_IMAGE_SIZE_POSTER}
      - NEXT_PUBLIC_TMDB_IMAGE_SIZE_BACKDROP=${NEXT_PUBLIC_TMDB_IMAGE_SIZE_BACKDROP}
      - NEXT_PUBLIC_VIDSRC_BASE_URL=${NEXT_PUBLIC_VIDSRC_BASE_URL}
      - NEXT_PUBLIC_VIDLINK_BASE_URL=${NEXT_PUBLIC_VIDLINK_BASE_URL}
    restart: unless-stopped
    networks:
      - movie-network

networks:
  movie-network:
    driver: bridge
